### PR TITLE
Fix windows build

### LINKED ISSUE #24: Bug: full file paths in coverage output (windows)
**Describe the bug**
It doesn't work on windows

**To Reproduce**
1. `go install github.com/orlangure/gocovsh@latest`
2. `cd Some/Directory`
3. `git clone https://github.com/tsoding/snitch`
4. `cd snitch`
5. `go test -v -cover -coverprofile coverage.out`
6. `gocovsh --profile coverage.out`
7. Enter on a selected file.

**Expected behavior**
File paths are relative in the cover.out file eg. `github.com/tsoding/snitch/logcmd.go:26.33,28.4 1 0`.
I don't think this issue is package-specific (snitch).

**Screenshots**
[Files](https://user-images.githubusercontent.com/29627898/155869956-60cc5a87-9659-4923-ace6-1fde68cdda7c.png)
[After Opening a file](https://user-images.githubusercontent.com/29627898/155869961-2ca14e42-e95e-4ddf-8ef2-749bbb0a8018.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Info: 
    ```go
      Edition	Windows 10 Home Single Language
      Version	21H1
      Installed on	‎8/‎7/‎2020
      OS build	19043.1566
      Experience	Windows Feature Experience Pack 120.2212.4170.0
    ```
 - Terminal emulator: cmd.exe, clink, alacritty

**Additional context**
Not sure if this is windows specific but I'm on windows.

### PR DESCRIPTION
**Pull request by phanirithvij**
closes #24

### CODE REVIEW

File: internal/program/program_test.go [hunk 1]
```diff
@@ -55,4 +56,9 @@ func TestLogger(t *testing.T) {
 	logs, err := os.ReadFile(f.Name())
 	require.NoError(t, err)
 	require.Contains(t, string(logs), "logging to")
+
+	if runtime.GOOS == "windows" {
+		// https://github.com/docker/compose/issues/8186#issuecomment-814180124
+		t.Log("Workaround for containerd/console bug")
```
Comment (phanirithvij) [inline internal/program/program_test.go:62]: Removing this causes this test to fail on windows with the errors
```go
=== FAIL: internal/program TestLogger (unknown)
failed to get console mode for stdout: The handle is invalid.
failed to get console mode for stderr: The handle is invalid.
```

This is a workaround which I found accidentally, trying to debug why this was occuring.
Tried vscode debugger first but the test succeeded, then tried the classic print debug and this seems to have fixed it.
Logging something using `t.Log()` in any line after line 53 i.e. `require.Error(t, p.Run())` seems to fix this.

**Comment by phanirithvij** [comment]
It happens because windows line feeds are CRLF `\r\n` and Linux, mac has LF `\n`.
Forcefully enabled LF for all files via `.gitattributes` will fix many of the tests.
Issue #24 occurs because `go.mod` files on windows could end with CRLF.
So that method can be fixed by replacing `\r\n` with `\n`. but I did it using `bufio.NewScanner`. I will change it to use `strings.ReplaceAll` instead.

**Comment by orlangure** [comment]
Thank you @phanirithvij, this looks amazing!

I will take a deeper look as soon as I can, but for now can you elaborate on why do we need separate golden files for windows builds? Are their terminal sequences different or something like that?

I'll properly review it a little later. Thanks!

File: internal/gocovshtest/testdata/errors/error_flows_missing_coverage_file_windows.golden [hunk 2]
```diff
@@ -0,0 +1,11 @@
+                          
+ [1;38;2;255;85;85mCoverage report not found[0m
+                                                                           
+ Requested coverage profile is not found.                                  
+ By default, "coverage.out" is used. For other names, use "--profile" flag.
+                                                                                
+ [38;2;192;192;192mThe original error was:[0m                                                        
+ [38;2;192;192;192mopen testdata/general/missing.cover: The system cannot find the file specified.[0m
```
Comment (phanirithvij) [inline internal/gocovshtest/testdata/errors/error_flows_missing_coverage_file_windows.golden:8]: I separated them because of the different error message windows has for file not found error. `The system cannot find the file specified` instead of `no such file or directory` like on linux and macos

File: internal/gocovshtest/errors_test.go [hunk 3]
```diff
@@ -73,7 +84,11 @@ func TestErrorFlows(t *testing.T) {
 		mm, cmd = mt.sendErrorMsg(initMsg)
 		require.NotNil(t, mm)
 		require.Nil(t, cmd)
-		g.Assert(t, "error_flows_invalid_coverage_file", []byte(mm.View()))
```
Comment (orlangure) [inline internal/gocovshtest/errors_test.go:76]: It appears that the error is the same on both platforms (it isn't "file not found" error, but a custom error representing a corrupted file).

File: internal/gocovshtest/testdata/errors/error_flows_invalid_coverage_file_windows.golden [hunk 4]
```diff
@@ -0,0 +1,11 @@
+
```
Comment (orlangure) [inline internal/gocovshtest/testdata/errors/error_flows_invalid_coverage_file_windows.golden:1]: If you agree that this file is the same as the non-windows file, please remove it.

**Review by orlangure — APPROVED** [review]
Thank you again for taking care of this bug.

Everything looks great, but I think that one of the added files is redundant. Correct me if I'm wrong. I'll wait for your answer before releasing a new version.

File: internal/gocovshtest/testdata/errors/error_flows_invalid_coverage_file_windows.golden (hunk 4 above)
Comment (phanirithvij) [reply internal/gocovshtest/testdata/errors/error_flows_invalid_coverage_file_windows.golden]: can you please re-review, I removed more unused files

Comment (phanirithvij) [reply internal/gocovshtest/testdata/errors/error_flows_invalid_coverage_file_windows.golden]: I also suggest a squash merge if you think that's appropriate here.

**Comment by orlangure** [comment]
Thank you for fixing this!
